### PR TITLE
more build system fixes for MGARD GPU

### PR DESCRIPTION
**Pull request by robertu94**
A couple of more fixes for the build system.

1) nvcomp's library is called `nvcomp::nvcomp` not `nvcomp` which can result in it not being found.  There is also a bug in their cmake package that I've have sent in a PR for here: https://github.com/NVIDIA/nvcomp/pull/45
2) libcudadevrt is linked implicitly by cmake 3.18 and later and explictly listing it here can cause both shared and static versions to be included causing build failures.
3) Most linux distributions include a newer version (and incompatible) of tclap than what you use here.  I provided a small patch to allow both of them to be used.
4) A formula in the documentation for ` include/TensorLinearOperator.hpp` causes compiler errors with new versions of NVCC if it is split on multiple lines.  I fixed it here and marked it so clang-format should ignore it's formatting since in this case the formatting matters
5) A few other minor changes to make clang-format happy

Lastly, there is a bug in the CMake's FindOpenMP.cmake that can cause build failures on systems with glibc 2.34 (i.e. Fedora 35) when used in conjunction with shared libraries and nvcc.  For details see https://gitlab.kitware.com/cmake/cmake/-/issues/22896  This bug doesn't require any code changes, but can be worked arround by configuring MGARD with -DOpenMP_pthread_LIBRARY=/usr/lib64/libpthread.so.0

### CODE REVIEW

**Review by ben-e-whitney — APPROVED** [review]
Thanks for the help, @robertu94, as always.

My only feedback concerns the TCLAP changes, and it's really just a heads up. The v1.2/v1.4 problem was encountered in #167, and I have pushed a few commits to the [`find-tclap`][find-tclap] branch to fix it. The approach I took there was to just upgrade to the newest version. I suggest that we merge your `TCLAP_USE_CONST` changes, and then I'll soon after make them unneeded by dropping v1.2 support.


[find-tclap]: https://github.com/CODARcode/MGARD/commits/find-tclap

@qliu21, if @JieyangChen7 approves the build changes I think we can merge this.

**Comment by JieyangChen7** [comment]
@qliu21 @ben-e-whitney I will check it out in a few days.

**Comment by JieyangChen7** [comment]
@qliu21 I approve this pull request. But we need to wait for https://github.com/NVIDIA/nvcomp/pull/45 to be merged before we merge this one.

**Review by JieyangChen7 — APPROVED** [review]

**Comment by ben-e-whitney** [comment]
Do we actually need NVIDIA/nvcomp#45 to be merged before we merge this? @robertu94's description of that pull request:

> Previously, the installed include directory was not added to the PUBLIC interface of the installed library preventing users from using find_package(nvcomp); target_link_libraries(foo PRIVATE nvcomp::nvcomp) if the library was installed to a non-standard include location (i.e. with `spack` or `~/.local/include`)

If I'm reading that correctly, the changes are only needed for the case where

1. `nvcomp` was installed to some nonstandard location and
2. `nvcomp` is being linked 'privately' (`target_link_libraries(foo PRIVATE nvcomp::nvcomp)`).

In MGARD, we're linking `nvcomp` 'publicly' (line 236 [here][nvcomp linking]: `target_link_libraries(mgard-library PUBLIC nvcomp::nvcomp CUDA::cudart )`), so maybe we're unaffected? @JieyangChen7, what happens when you try to build on 3c05c80a45a51bb6cc5fb5fffe7b1b16787d3366?

[nvcomp linking]: https://github.com/CODARcode/MGARD/pull/168/commits/0af3e2b608ba21c15622a27130c476a182c41fa3

**Comment by robertu94** [comment]
@ben-e-whitney the problem is not that MGARD links nvcomp publically vs privately, but that NVCOMP didn't set it's include flags in a way that MGARD could find them (which is what the linked NVCOMP PR does).  If your NVCOMP is installed to a standard location (i.e. /opt/cuda ) then I expect it works fine because it will find it installed to the same place as nvidia's libraries or in the system include directory.  However since I and spack put nvcomp and cuda in non-standard places, this causes problems.

**Comment by robertu94** [comment]
@ben-e-whitney Update from the NVCOMP PR indicates the fix to NVCOMP should be included in the next release targeted end of January/Feburary.

**Comment by ben-e-whitney** [comment]
> the problem is not that MGARD links nvcomp publically vs privately, but that NVCOMP didn't set it's include flags in a way that MGARD could find them (which is what the linked NVCOMP PR does). If your NVCOMP is installed to a standard location (i.e. /opt/cuda ) then I expect it works fine because it will find it installed to the same place as nvidia's libraries or in the system include directory. However since I and spack put nvcomp and cuda in non-standard places, this causes problems.

Is it right, then, that there's no problem with merging this PR before merging the one you made to `nvcomp`? My understanding is that the two PRs are orthogonal.

> Update from the NVCOMP PR indicates the fix to NVCOMP should be included in the next release targeted end of January/Feburary.

Great. Worst case scenario, then, we can merge this in February. It'd be nice to merge it earlier, though.

**Comment by ben-e-whitney** [comment]
I checked with @JieyangChen7 again and he said we should wait for the `nvcomp` pull request to be merged. In the meantime, I will merge some other code, including an upgrade to TCLAP v1.4 that will make the TCLAP changes in 0af3e2b608ba21c15622a27130c476a182c41fa3 unneeded. After we merge this pull request, I'll revert those changes in 0af3e2b608ba21c15622a27130c476a182c41fa3.

**Comment by JieyangChen7** [comment]
@ben-e-whitney @qliu21 I already included some GPU build fixes in my recent PRs. Do we still need to merge this PR? Besides the GPU build fix, I see some changes to the CLI in this PR, but I'm not sure if we still need those.

**Comment by ben-e-whitney** [comment]
I rebased these commits and pushed the results to [`underwood-master`][comparison]. Summary of changes:

1. In #169 we switched to TCLAP v1.4, making the compatibility patch unnecessary (assuming no one tries to build the project with TCLAP v1.2), so I removed it.
2. The `nvcomp::nvcomp` change was 'already' (later in time but earlier in the Git history) made in 2fc643b76d1f7b9122e2cc04389636a8241b34c0.
3. As a result of the two preceding changes, the first commit (0af3e2b608ba21c15622a27130c476a182c41fa3 in `robertu94/master` and 26eaa209f3d8ddfb6291b39b64c60e9d2f5ff921 in `CODARcode/underwood-master`) now makes no build-related changes, so I changed the commit message to 'Add missing includes and fix formatting issue.' @robertu94, please let me know if you're OK with that (you're still the author of the commit).
4. The `MGARD_ENABLE_CUDA_OPTIMIZE_{VOLTA,TURING}` options are no longer used as of 0293c2450f0dbcac21fe6d402053e8b2685342ce (they're still defined – @JieyangChen7, is this intentional?), so I've removed the related changes in the second commit (3c05c80a45a51bb6cc5fb5fffe7b1b16787d3366 in `robertu94/master` and e74ba9ba293243f3aac8b57e356f7a6763560f19  in `CODARcode/underwood-master`).
5. I've moved the 'declaration' of `mgard-library` to before the first `target_compile_definitions(mgard-library …)` call.

@robertu94, if this looks good to you, can you update your branch? I think something like this should work:

```console
$ git fetch upstream underwood-master
$ git push --force origin upstream/underwood-master:master
```

[comparison]: https://github.com/CODARcode/MGARD/compare/underwood-master

**Comment by JieyangChen7** [comment]
@ben-e-whitney The `MGARD_ENABLE_CUDA_OPTIMIZE_{VOLTA,TURING}` options are deprecated. It is fine to remove their definitions.

**Comment by robertu94** [comment]
@ben-e-whitney I tried to merge your changes this morning, and got a merge conflict.  I've been heads down on the papers my team is submitting to SC.  I hope to get to this when I get to the "waiting on the cluster" phase of writing a paper, but otherwise I might not get to this until after April 1.

**Comment by ben-e-whitney** [comment]
@robertu94 Thanks for letting us know. What if we just merge the version of the commits in `underwood-master`? The only thing you'd really need to check is that you're OK with the changed commit message (you're still the author of the commits). The change: 'more build system fixes for MGARD GPU' to 'Add missing includes and fix formatting issue.'

 Good luck with your papers!

**Comment by robertu94** [comment]
@ben-e-whitney im ok with you changing the commit message.

**Comment by ben-e-whitney** [comment]
Thanks, @robertu94. I'll close this pull request. @qliu21, please merge #183 in its place.

**Pull request closed without merging**
