### PR TITLE
CPU and GPU code to run XGC examples 

### PR DESCRIPTION
**Pull request by gqian-coder**
Hi Gary,

I created a GPU MGARD-XGC example code under test/gpu-cuda. I modified jieyang's CMake file to compile the example code together with his other testing code. I also added a folder called xgc-casestudy under the examples directory. They are CPU examples to reproduce some of the results in my SMC paper.

Let me know if I need to make any changes for the code to go with release.

Qian

### CODE REVIEW

**Comment by qliu21** [comment]
@gqian-coder Thanks! Some of the examples here have hard-coded path. Do you want to clean it up?

**Comment by gqian-coder** [comment]
@qliu21 Hi, Gary, may I know which file path do you mean? Like the "RsQ.bp"?

**Comment by qliu21** [comment]
@gqian-coder Please fix the coding format using clang-format, which should be straightforward.

**Comment by qliu21** [comment]
@gqian-coder It looks like this PR has conflicts on tests/gpu-cuda/CMakeLists.txt, which needs to be manually resolved.

**Comment by gqian-coder** [comment]
I added the following two lines in the tests/gpu-cuda/CMakeLists.txt to
include my TestXGC example code:
add_executable(TestXGCAbsoluteError TestXGCAbsoluteError.cpp)
target_link_libraries(TestXGCAbsoluteError adios2::adios2 mgard::mgard
MPI::MPI_CXX)

Any way to manually fix that conflict?

Qian

**Comment by ben-e-whitney** [comment]
I rebased and fixed the merge conflict. It should be good to go now.

**Pull request merged**
