### PR TITLE
MGARD cuda release 07/2020

### PR DESCRIPTION
**Pull request by cjy7117**
This pull request contains the first CUDA accelerated MGARD implementation. Here is a list of changes:
1) added src/cuda and include/cuda for CUDA implementations
2) added include/mgard_cuda_api.h for user header file
3) modified CMakeList.txt to enable CUDA. A switch is added for uses to turn CUDA ON/OFF as desired with an optional switch to also turn on CUDA debug mode.
4) a test program is provided bin/mgard_check_cuda_and_cpu to help compare the correctness of the CUDA and CPU implementation.
5) currently only L_inf norm compression is supported. The support of s norm will be added later.
Please let me know if I need to improve any parts. Thanks.

### CODE REVIEW

**Comment by qliu21** [comment]
Jieyang, make sure you can pass the tests so that I can merge it.

**Comment by cjy7117** [comment]
Hi Gary, all CI checks are passing now. Please let me know if I need to do anything. Thanks.

**Comment by qliu21** [comment]
@cjy7117 sorry for the delay. Had some other deadlines. It looks like there are conflicts in this PR so it can be merged easily. Please resolve.

**Comment by cjy7117** [comment]
@qliu21 Thanks. But I do not see any conflict warning showing on my side. I also tested it by doing offline merge on my machines. It shows that they can merge without conflicts. May I ask how should I reveal those conflicts?

**Comment by qliu21** [comment]
@cjy7117 it looks like if I "rebase and merge", it says that "This branch cannot be rebased due to conflicts
Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch."

I don't have more info beyond this. But if I "squash and merge", it looks like there is no conflict. Are you okay with "squash and merge"?

**Comment by cjy7117** [comment]
@qliu21 Ok, I'm fine with "squash and merge" for this time. I will keep all commit history in my branch so they will not be lost. Once this master branch is merged I will used it create a new base branch for my development works so that it can be easily "rebase and merge" in the future.

**Pull request merged**
