### PR TITLE
Use Protobuf in MGARD-X & Add MDR-X

### PR DESCRIPTION
**Pull request by JieyangChen7**
This should be the last major PR before the March release.

### CODE REVIEW

**Comment by JieyangChen7** [comment]
@ben-e-whitney Please review my changes to `mgard.proto` and other related changes in the CPU version. Thanks!

**Comment by ben-e-whitney** [comment]
Looks good to me. Two things:

1. This is very small, but I suggest we replace `NO_SHUFFLE` and `NOOP` in `Encoding::Preprocessor` and `Encoding::Compressor` with `NOOP_PREPROCESSOR` and `NOOP_COMPRESSOR`, respectively. Then I suggest we replace `NOOP` in `DomainDecomposition::Method` with `NOOP_METHOD` for consistency. (It's the numeric values that matter for the buffers, so we aren't locked in to anything here.)
2. What is the purpose of the `Device` message? I want to make sure we don't end up in a situation where, for example, `X_HUFFMAN_LZ4` is implemented slightly differently on `CUDA` than on `HIP` and so we need to refer to `Device` to decompress correctly. If we're just storing the backend like you might a timestamp (doesn't change any behavior, but might be good to know), I think that's fine.

**Comment by JieyangChen7** [comment]
@ben-e-whitney Thanks for reviewing my changes. I have revised `mgard.proto` according to your suggestions. The purpose of the `Device` message is just for letting us know which device (backend) was used for compression. It does not change any behavior. This information might be useful for us to quickly locate a backend that potentially contains a bug. Please let me know if you have any more suggestions. I plan to merge this PR early next week. Thanks!

**Comment by JieyangChen7** [comment]
@qliu21 I'm trying to merge this PR. Which merge option do you usually choose `Create a merge commit` or `Rebase and merge`?

**Pull request merged**
