### PR TITLE
Rework Test Script and Instantiate Templates

### PR DESCRIPTION
**Pull request by ben-e-whitney**
Compilation times should improve after these commits are merged. I had made a syntax error in the template instantiations and so the functions were getting recompiled whenever a source file `include`d them.

### CODE REVIEW

**Comment by ben-e-whitney** [comment]
Is there a way to run the CI tests locally? It looks like one of the tests is failing because it didn't include `iostream`. I am happy to fix it, but it will take forever if I have to check every change by pushing and waiting.

**Comment by qliu21** [comment]
@ben-e-whitney I haven't done the tests locally. But I found this...looks like it can be done.

https://stackoverflow.com/questions/21053657/how-to-run-travis-ci-locally

**Comment by ben-e-whitney** [comment]
Unfortunately I wasn't able to get that to work. I did manage to get the tests passing, though.

I will rebase once #61 is merged.

**Comment by ben-e-whitney** [comment]
OK, @qliu21, this is ready for review.

**Pull request merged**
